/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type ErrorsAndWarningsStruct = {
  errors: PromiseOrValue<BigNumberish>[];
  warnings: PromiseOrValue<BigNumberish>[];
};

export type ErrorsAndWarningsStructOutput = [number[], number[]] & {
  errors: number[];
  warnings: number[];
};

export type OfferItemStruct = {
  itemType: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  identifierOrCriteria: PromiseOrValue<BigNumberish>;
  startAmount: PromiseOrValue<BigNumberish>;
  endAmount: PromiseOrValue<BigNumberish>;
};

export type OfferItemStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  itemType: number;
  token: string;
  identifierOrCriteria: BigNumber;
  startAmount: BigNumber;
  endAmount: BigNumber;
};

export type ConsiderationItemStruct = {
  itemType: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  identifierOrCriteria: PromiseOrValue<BigNumberish>;
  startAmount: PromiseOrValue<BigNumberish>;
  endAmount: PromiseOrValue<BigNumberish>;
  recipient: PromiseOrValue<string>;
};

export type ConsiderationItemStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  itemType: number;
  token: string;
  identifierOrCriteria: BigNumber;
  startAmount: BigNumber;
  endAmount: BigNumber;
  recipient: string;
};

export type OrderParametersStruct = {
  offerer: PromiseOrValue<string>;
  zone: PromiseOrValue<string>;
  offer: OfferItemStruct[];
  consideration: ConsiderationItemStruct[];
  orderType: PromiseOrValue<BigNumberish>;
  startTime: PromiseOrValue<BigNumberish>;
  endTime: PromiseOrValue<BigNumberish>;
  zoneHash: PromiseOrValue<BytesLike>;
  salt: PromiseOrValue<BigNumberish>;
  conduitKey: PromiseOrValue<BytesLike>;
  totalOriginalConsiderationItems: PromiseOrValue<BigNumberish>;
};

export type OrderParametersStructOutput = [
  string,
  string,
  OfferItemStructOutput[],
  ConsiderationItemStructOutput[],
  number,
  BigNumber,
  BigNumber,
  string,
  BigNumber,
  string,
  BigNumber
] & {
  offerer: string;
  zone: string;
  offer: OfferItemStructOutput[];
  consideration: ConsiderationItemStructOutput[];
  orderType: number;
  startTime: BigNumber;
  endTime: BigNumber;
  zoneHash: string;
  salt: BigNumber;
  conduitKey: string;
  totalOriginalConsiderationItems: BigNumber;
};

export type OrderStruct = {
  parameters: OrderParametersStruct;
  signature: PromiseOrValue<BytesLike>;
};

export type OrderStructOutput = [OrderParametersStructOutput, string] & {
  parameters: OrderParametersStructOutput;
  signature: string;
};

export type ValidationConfigurationStruct = {
  seaport: PromiseOrValue<string>;
  primaryFeeRecipient: PromiseOrValue<string>;
  primaryFeeBips: PromiseOrValue<BigNumberish>;
  checkCreatorFee: PromiseOrValue<boolean>;
  skipStrictValidation: PromiseOrValue<boolean>;
  shortOrderDuration: PromiseOrValue<BigNumberish>;
  distantOrderExpiration: PromiseOrValue<BigNumberish>;
};

export type ValidationConfigurationStructOutput = [
  string,
  string,
  BigNumber,
  boolean,
  boolean,
  BigNumber,
  BigNumber
] & {
  seaport: string;
  primaryFeeRecipient: string;
  primaryFeeBips: BigNumber;
  checkCreatorFee: boolean;
  skipStrictValidation: boolean;
  shortOrderDuration: BigNumber;
  distantOrderExpiration: BigNumber;
};

export type SpentItemStruct = {
  itemType: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  identifier: PromiseOrValue<BigNumberish>;
  amount: PromiseOrValue<BigNumberish>;
};

export type SpentItemStructOutput = [number, string, BigNumber, BigNumber] & {
  itemType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
};

export type ReceivedItemStruct = {
  itemType: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  identifier: PromiseOrValue<BigNumberish>;
  amount: PromiseOrValue<BigNumberish>;
  recipient: PromiseOrValue<string>;
};

export type ReceivedItemStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  itemType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
  recipient: string;
};

export type ZoneParametersStruct = {
  orderHash: PromiseOrValue<BytesLike>;
  fulfiller: PromiseOrValue<string>;
  offerer: PromiseOrValue<string>;
  offer: SpentItemStruct[];
  consideration: ReceivedItemStruct[];
  extraData: PromiseOrValue<BytesLike>;
  orderHashes: PromiseOrValue<BytesLike>[];
  startTime: PromiseOrValue<BigNumberish>;
  endTime: PromiseOrValue<BigNumberish>;
  zoneHash: PromiseOrValue<BytesLike>;
};

export type ZoneParametersStructOutput = [
  string,
  string,
  string,
  SpentItemStructOutput[],
  ReceivedItemStructOutput[],
  string,
  string[],
  BigNumber,
  BigNumber,
  string
] & {
  orderHash: string;
  fulfiller: string;
  offerer: string;
  offer: SpentItemStructOutput[];
  consideration: ReceivedItemStructOutput[];
  extraData: string;
  orderHashes: string[];
  startTime: BigNumber;
  endTime: BigNumber;
  zoneHash: string;
};

export interface SeaportValidatorInterface extends utils.Interface {
  functions: {
    "CONTRACT_OFFERER_INTERFACE_ID()": FunctionFragment;
    "ERC1155_INTERFACE_ID()": FunctionFragment;
    "ERC20_INTERFACE_ID()": FunctionFragment;
    "ERC721_INTERFACE_ID()": FunctionFragment;
    "ZONE_INTERFACE_ID()": FunctionFragment;
    "checkInterface(address,bytes4)": FunctionFragment;
    "getApprovalAddress(bytes32,address)": FunctionFragment;
    "getMerkleProof(uint256[],uint256)": FunctionFragment;
    "getMerkleRoot(uint256[])": FunctionFragment;
    "isPaymentToken(uint8)": FunctionFragment;
    "isValidConduit(bytes32,address)": FunctionFragment;
    "isValidOrder(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes),address)": FunctionFragment;
    "isValidOrderWithConfiguration((address,address,uint256,bool,bool,uint256,uint256),((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes))": FunctionFragment;
    "isValidZone((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256))": FunctionFragment;
    "sortMerkleTokens(uint256[])": FunctionFragment;
    "validateConsiderationItem((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,address)": FunctionFragment;
    "validateConsiderationItemParameters((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,address)": FunctionFragment;
    "validateConsiderationItems((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),address)": FunctionFragment;
    "validateContractOfferer(address)": FunctionFragment;
    "validateOfferItem((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,address)": FunctionFragment;
    "validateOfferItemApprovalAndBalance((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,address)": FunctionFragment;
    "validateOfferItemParameters((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,address)": FunctionFragment;
    "validateOfferItems((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),address)": FunctionFragment;
    "validateOrderStatus((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),address)": FunctionFragment;
    "validateOrderWithZone((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),(bytes32,address,address,(uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[],bytes,bytes32[],uint256,uint256,bytes32))": FunctionFragment;
    "validateSignature(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes),address)": FunctionFragment;
    "validateSignatureWithCounter(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes),uint256,address)": FunctionFragment;
    "validateStrictLogic((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),address,uint256,bool)": FunctionFragment;
    "validateTime((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint256,uint256)": FunctionFragment;
    "verifyMerkleProof(bytes32,bytes32[],uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CONTRACT_OFFERER_INTERFACE_ID"
      | "ERC1155_INTERFACE_ID"
      | "ERC20_INTERFACE_ID"
      | "ERC721_INTERFACE_ID"
      | "ZONE_INTERFACE_ID"
      | "checkInterface"
      | "getApprovalAddress"
      | "getMerkleProof"
      | "getMerkleRoot"
      | "isPaymentToken"
      | "isValidConduit"
      | "isValidOrder"
      | "isValidOrderWithConfiguration"
      | "isValidZone"
      | "sortMerkleTokens"
      | "validateConsiderationItem"
      | "validateConsiderationItemParameters"
      | "validateConsiderationItems"
      | "validateContractOfferer"
      | "validateOfferItem"
      | "validateOfferItemApprovalAndBalance"
      | "validateOfferItemParameters"
      | "validateOfferItems"
      | "validateOrderStatus"
      | "validateOrderWithZone"
      | "validateSignature"
      | "validateSignatureWithCounter"
      | "validateStrictLogic"
      | "validateTime"
      | "verifyMerkleProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CONTRACT_OFFERER_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1155_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC20_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZONE_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkInterface",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovalAddress",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleProof",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRoot",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentToken",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidConduit",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidOrder",
    values: [OrderStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidOrderWithConfiguration",
    values: [ValidationConfigurationStruct, OrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidZone",
    values: [OrderParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "sortMerkleTokens",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateConsiderationItem",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateConsiderationItemParameters",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateConsiderationItems",
    values: [OrderParametersStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateContractOfferer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOfferItem",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOfferItemApprovalAndBalance",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOfferItemParameters",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOfferItems",
    values: [OrderParametersStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOrderStatus",
    values: [OrderParametersStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOrderWithZone",
    values: [OrderParametersStruct, ZoneParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSignature",
    values: [OrderStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSignatureWithCounter",
    values: [OrderStruct, PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateStrictLogic",
    values: [
      OrderParametersStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTime",
    values: [
      OrderParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMerkleProof",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "CONTRACT_OFFERER_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1155_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC20_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZONE_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidConduit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidOrderWithConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidZone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sortMerkleTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateConsiderationItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateConsiderationItemParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateConsiderationItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateContractOfferer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOfferItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOfferItemApprovalAndBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOfferItemParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOfferItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOrderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOrderWithZone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSignatureWithCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateStrictLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMerkleProof",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SeaportValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SeaportValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CONTRACT_OFFERER_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    ERC1155_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    ERC20_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    ERC721_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    ZONE_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    checkInterface(
      token: PromiseOrValue<string>,
      interfaceHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getApprovalAddress(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    getMerkleProof(
      includedTokens: PromiseOrValue<BigNumberish>[],
      targetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string[], ErrorsAndWarningsStructOutput] & {
        merkleProof: string[];
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    getMerkleRoot(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [string, ErrorsAndWarningsStructOutput] & {
        merkleRoot: string;
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    isPaymentToken(
      itemType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidConduit(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    isValidOrder(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    isValidOrderWithConfiguration(
      validationConfiguration: ValidationConfigurationStruct,
      order: OrderStruct,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    isValidZone(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    sortMerkleTokens(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { sortedTokens: BigNumber[] }>;

    validateConsiderationItem(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateConsiderationItemParameters(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateConsiderationItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateContractOfferer(
      contractOfferer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOfferItem(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOfferItemApprovalAndBalance(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOfferItemParameters(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOfferItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOrderStatus(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateOrderWithZone(
      orderParameters: OrderParametersStruct,
      zoneParameters: ZoneParametersStruct,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateSignature(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateSignatureWithCounter(
      order: OrderStruct,
      counter: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateStrictLogic(
      orderParameters: OrderParametersStruct,
      primaryFeeRecipient: PromiseOrValue<string>,
      primaryFeeBips: PromiseOrValue<BigNumberish>,
      checkCreatorFee: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    validateTime(
      orderParameters: OrderParametersStruct,
      shortOrderDuration: PromiseOrValue<BigNumberish>,
      distantOrderExpiration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    verifyMerkleProof(
      merkleRoot: PromiseOrValue<BytesLike>,
      merkleProof: PromiseOrValue<BytesLike>[],
      valueToProve: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  CONTRACT_OFFERER_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  ERC1155_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  ERC20_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  ERC721_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  ZONE_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  checkInterface(
    token: PromiseOrValue<string>,
    interfaceHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getApprovalAddress(
    conduitKey: PromiseOrValue<BytesLike>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, ErrorsAndWarningsStructOutput] & {
      errorsAndWarnings: ErrorsAndWarningsStructOutput;
    }
  >;

  getMerkleProof(
    includedTokens: PromiseOrValue<BigNumberish>[],
    targetIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string[], ErrorsAndWarningsStructOutput] & {
      merkleProof: string[];
      errorsAndWarnings: ErrorsAndWarningsStructOutput;
    }
  >;

  getMerkleRoot(
    includedTokens: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [string, ErrorsAndWarningsStructOutput] & {
      merkleRoot: string;
      errorsAndWarnings: ErrorsAndWarningsStructOutput;
    }
  >;

  isPaymentToken(
    itemType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidConduit(
    conduitKey: PromiseOrValue<BytesLike>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  isValidOrder(
    order: OrderStruct,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  isValidOrderWithConfiguration(
    validationConfiguration: ValidationConfigurationStruct,
    order: OrderStruct,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  isValidZone(
    orderParameters: OrderParametersStruct,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  sortMerkleTokens(
    includedTokens: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  validateConsiderationItem(
    orderParameters: OrderParametersStruct,
    considerationItemIndex: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateConsiderationItemParameters(
    orderParameters: OrderParametersStruct,
    considerationItemIndex: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateConsiderationItems(
    orderParameters: OrderParametersStruct,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateContractOfferer(
    contractOfferer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOfferItem(
    orderParameters: OrderParametersStruct,
    offerItemIndex: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOfferItemApprovalAndBalance(
    orderParameters: OrderParametersStruct,
    offerItemIndex: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOfferItemParameters(
    orderParameters: OrderParametersStruct,
    offerItemIndex: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOfferItems(
    orderParameters: OrderParametersStruct,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOrderStatus(
    orderParameters: OrderParametersStruct,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateOrderWithZone(
    orderParameters: OrderParametersStruct,
    zoneParameters: ZoneParametersStruct,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateSignature(
    order: OrderStruct,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateSignatureWithCounter(
    order: OrderStruct,
    counter: PromiseOrValue<BigNumberish>,
    seaportAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateStrictLogic(
    orderParameters: OrderParametersStruct,
    primaryFeeRecipient: PromiseOrValue<string>,
    primaryFeeBips: PromiseOrValue<BigNumberish>,
    checkCreatorFee: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  validateTime(
    orderParameters: OrderParametersStruct,
    shortOrderDuration: PromiseOrValue<BigNumberish>,
    distantOrderExpiration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ErrorsAndWarningsStructOutput>;

  verifyMerkleProof(
    merkleRoot: PromiseOrValue<BytesLike>,
    merkleProof: PromiseOrValue<BytesLike>[],
    valueToProve: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    CONTRACT_OFFERER_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    ERC1155_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    ERC20_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    ERC721_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    ZONE_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    checkInterface(
      token: PromiseOrValue<string>,
      interfaceHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getApprovalAddress(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, ErrorsAndWarningsStructOutput] & {
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    getMerkleProof(
      includedTokens: PromiseOrValue<BigNumberish>[],
      targetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string[], ErrorsAndWarningsStructOutput] & {
        merkleProof: string[];
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    getMerkleRoot(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [string, ErrorsAndWarningsStructOutput] & {
        merkleRoot: string;
        errorsAndWarnings: ErrorsAndWarningsStructOutput;
      }
    >;

    isPaymentToken(
      itemType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidConduit(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    isValidOrder(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    isValidOrderWithConfiguration(
      validationConfiguration: ValidationConfigurationStruct,
      order: OrderStruct,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    isValidZone(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    sortMerkleTokens(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    validateConsiderationItem(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateConsiderationItemParameters(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateConsiderationItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateContractOfferer(
      contractOfferer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOfferItem(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOfferItemApprovalAndBalance(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOfferItemParameters(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOfferItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOrderStatus(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateOrderWithZone(
      orderParameters: OrderParametersStruct,
      zoneParameters: ZoneParametersStruct,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateSignature(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateSignatureWithCounter(
      order: OrderStruct,
      counter: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateStrictLogic(
      orderParameters: OrderParametersStruct,
      primaryFeeRecipient: PromiseOrValue<string>,
      primaryFeeBips: PromiseOrValue<BigNumberish>,
      checkCreatorFee: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    validateTime(
      orderParameters: OrderParametersStruct,
      shortOrderDuration: PromiseOrValue<BigNumberish>,
      distantOrderExpiration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ErrorsAndWarningsStructOutput>;

    verifyMerkleProof(
      merkleRoot: PromiseOrValue<BytesLike>,
      merkleProof: PromiseOrValue<BytesLike>[],
      valueToProve: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    CONTRACT_OFFERER_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC1155_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    ERC20_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    ERC721_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    ZONE_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    checkInterface(
      token: PromiseOrValue<string>,
      interfaceHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getApprovalAddress(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerkleProof(
      includedTokens: PromiseOrValue<BigNumberish>[],
      targetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerkleRoot(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPaymentToken(
      itemType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidConduit(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidOrder(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidOrderWithConfiguration(
      validationConfiguration: ValidationConfigurationStruct,
      order: OrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidZone(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sortMerkleTokens(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateConsiderationItem(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateConsiderationItemParameters(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateConsiderationItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateContractOfferer(
      contractOfferer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOfferItem(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOfferItemApprovalAndBalance(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOfferItemParameters(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOfferItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOrderStatus(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOrderWithZone(
      orderParameters: OrderParametersStruct,
      zoneParameters: ZoneParametersStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateSignature(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateSignatureWithCounter(
      order: OrderStruct,
      counter: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateStrictLogic(
      orderParameters: OrderParametersStruct,
      primaryFeeRecipient: PromiseOrValue<string>,
      primaryFeeBips: PromiseOrValue<BigNumberish>,
      checkCreatorFee: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateTime(
      orderParameters: OrderParametersStruct,
      shortOrderDuration: PromiseOrValue<BigNumberish>,
      distantOrderExpiration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyMerkleProof(
      merkleRoot: PromiseOrValue<BytesLike>,
      merkleProof: PromiseOrValue<BytesLike>[],
      valueToProve: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CONTRACT_OFFERER_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC1155_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC20_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC721_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ZONE_INTERFACE_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkInterface(
      token: PromiseOrValue<string>,
      interfaceHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApprovalAddress(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMerkleProof(
      includedTokens: PromiseOrValue<BigNumberish>[],
      targetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMerkleRoot(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPaymentToken(
      itemType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidConduit(
      conduitKey: PromiseOrValue<BytesLike>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidOrder(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidOrderWithConfiguration(
      validationConfiguration: ValidationConfigurationStruct,
      order: OrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidZone(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sortMerkleTokens(
      includedTokens: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateConsiderationItem(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateConsiderationItemParameters(
      orderParameters: OrderParametersStruct,
      considerationItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateConsiderationItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateContractOfferer(
      contractOfferer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOfferItem(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOfferItemApprovalAndBalance(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOfferItemParameters(
      orderParameters: OrderParametersStruct,
      offerItemIndex: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOfferItems(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOrderStatus(
      orderParameters: OrderParametersStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOrderWithZone(
      orderParameters: OrderParametersStruct,
      zoneParameters: ZoneParametersStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateSignature(
      order: OrderStruct,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateSignatureWithCounter(
      order: OrderStruct,
      counter: PromiseOrValue<BigNumberish>,
      seaportAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateStrictLogic(
      orderParameters: OrderParametersStruct,
      primaryFeeRecipient: PromiseOrValue<string>,
      primaryFeeBips: PromiseOrValue<BigNumberish>,
      checkCreatorFee: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateTime(
      orderParameters: OrderParametersStruct,
      shortOrderDuration: PromiseOrValue<BigNumberish>,
      distantOrderExpiration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyMerkleProof(
      merkleRoot: PromiseOrValue<BytesLike>,
      merkleProof: PromiseOrValue<BytesLike>[],
      valueToProve: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
