/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImmutableCreate2FactoryInterface } from "./ImmutableCreate2FactoryInterface";
export type { ZoneInteractionErrors } from "./ZoneInteractionErrors";
export type { ZoneInterface } from "./ZoneInterface";
